/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiTrainingRouteImport } from './routes/ai-training'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as IndexRouteImport } from './routes/index'

const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/ai-training',
  path: '/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-training': typeof AiTrainingRoute
  '/performance': typeof PerformanceRoute
  '/agenda': typeof AgendaRoute
  '/chat': typeof ChatRoute
  '/kanban': typeof KanbanRoute
  '/marketing': typeof MarketingRoute
  '/saas': typeof SaasRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-training': typeof AiTrainingRoute
  '/performance': typeof PerformanceRoute
  '/agenda': typeof AgendaRoute
  '/chat': typeof ChatRoute
  '/kanban': typeof KanbanRoute
  '/marketing': typeof MarketingRoute
  '/saas': typeof SaasRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/performance': typeof PerformanceRoute
  '/agenda': typeof AgendaRoute
  '/chat': typeof ChatRoute
  '/kanban': typeof KanbanRoute
  '/marketing': typeof MarketingRoute
  '/saas': typeof SaasRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/performance'
    | '/agenda'
    | '/chat'
    | '/kanban'
    | '/marketing'
    | '/saas'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/performance'
    | '/agenda'
    | '/chat'
    | '/kanban'
    | '/marketing'
    | '/saas'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/performance'
    | '/agenda'
    | '/chat'
    | '/kanban'
    | '/marketing'
    | '/saas'
    | '/settings'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerformanceRoute: typeof PerformanceRoute
  AgendaRoute: typeof AgendaRoute
  ChatRoute: typeof ChatRoute
  KanbanRoute: typeof KanbanRoute
  MarketingRoute: typeof MarketingRoute
  SaasRoute: typeof SaasRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerformanceRoute: PerformanceRoute,
  AgendaRoute: AgendaRoute,
  ChatRoute: ChatRoute,
  KanbanRoute: KanbanRoute,
  MarketingRoute: MarketingRoute,
  SaasRoute: SaasRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
