/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BiRouteImport } from './routes/bi'
import { Route as AiTrainingRouteImport } from './routes/ai-training'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios.index'
import { Route as RelatoriosPerdidosRouteImport } from './routes/relatorios.perdidos'
import { Route as RelatoriosLtvRouteImport } from './routes/relatorios.ltv'
import { Route as RelatoriosComparecimentoRouteImport } from './routes/relatorios.comparecimento'
import { Route as RelatoriosAtendentesRouteImport } from './routes/relatorios.atendentes'
import { Route as RelatoriosAgendamentosRouteImport } from './routes/relatorios.agendamentos'
import { Route as AnalyticsNoShowRouteImport } from './routes/analytics/no-show'
import { Route as ApiAiTrainingSimulateChatRouteImport } from './routes/api/ai-training/simulate-chat'
import { Route as ApiPublicHooksProcessNoshowAlertsRouteImport } from './routes/api/public/hooks/process-noshow-alerts'
import { Route as ApiPublicHooksProcessFollowupsRouteImport } from './routes/api/public/hooks/process-followups'
import { Route as ApiPublicHooksProcessAppointmentRemindersRouteImport } from './routes/api/public/hooks/process-appointment-reminders'
import { Route as ApiPublicHooksEnrollSilentLeadsRouteImport } from './routes/api/public/hooks/enroll-silent-leads'
import { Route as ApiPublicHooksBuildReferenceStyleRouteImport } from './routes/api/public/hooks/build-reference-style'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/ai-training',
  path: '/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosPerdidosRoute = RelatoriosPerdidosRouteImport.update({
  id: '/perdidos',
  path: '/perdidos',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosLtvRoute = RelatoriosLtvRouteImport.update({
  id: '/ltv',
  path: '/ltv',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosComparecimentoRoute =
  RelatoriosComparecimentoRouteImport.update({
    id: '/comparecimento',
    path: '/comparecimento',
    getParentRoute: () => RelatoriosRoute,
  } as any)
const RelatoriosAtendentesRoute = RelatoriosAtendentesRouteImport.update({
  id: '/atendentes',
  path: '/atendentes',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosAgendamentosRoute = RelatoriosAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => RelatoriosRoute,
} as any)
const AnalyticsNoShowRoute = AnalyticsNoShowRouteImport.update({
  id: '/analytics/no-show',
  path: '/analytics/no-show',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTrainingSimulateChatRoute =
  ApiAiTrainingSimulateChatRouteImport.update({
    id: '/api/ai-training/simulate-chat',
    path: '/api/ai-training/simulate-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessNoshowAlertsRoute =
  ApiPublicHooksProcessNoshowAlertsRouteImport.update({
    id: '/api/public/hooks/process-noshow-alerts',
    path: '/api/public/hooks/process-noshow-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessFollowupsRoute =
  ApiPublicHooksProcessFollowupsRouteImport.update({
    id: '/api/public/hooks/process-followups',
    path: '/api/public/hooks/process-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessAppointmentRemindersRoute =
  ApiPublicHooksProcessAppointmentRemindersRouteImport.update({
    id: '/api/public/hooks/process-appointment-reminders',
    path: '/api/public/hooks/process-appointment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnrollSilentLeadsRoute =
  ApiPublicHooksEnrollSilentLeadsRouteImport.update({
    id: '/api/public/hooks/enroll-silent-leads',
    path: '/api/public/hooks/enroll-silent-leads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBuildReferenceStyleRoute =
  ApiPublicHooksBuildReferenceStyleRouteImport.update({
    id: '/api/public/hooks/build-reference-style',
    path: '/api/public/hooks/build-reference-style',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/bi': typeof BiRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/equipe': typeof EquipeRoute
  '/fila': typeof FilaRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/metas': typeof MetasRoute
  '/performance': typeof PerformanceRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/resultados': typeof ResultadosRoute
  '/saas': typeof SaasRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/analytics/no-show': typeof AnalyticsNoShowRoute
  '/relatorios/agendamentos': typeof RelatoriosAgendamentosRoute
  '/relatorios/atendentes': typeof RelatoriosAtendentesRoute
  '/relatorios/comparecimento': typeof RelatoriosComparecimentoRoute
  '/relatorios/ltv': typeof RelatoriosLtvRoute
  '/relatorios/perdidos': typeof RelatoriosPerdidosRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/api/ai-training/simulate-chat': typeof ApiAiTrainingSimulateChatRoute
  '/api/public/hooks/build-reference-style': typeof ApiPublicHooksBuildReferenceStyleRoute
  '/api/public/hooks/enroll-silent-leads': typeof ApiPublicHooksEnrollSilentLeadsRoute
  '/api/public/hooks/process-appointment-reminders': typeof ApiPublicHooksProcessAppointmentRemindersRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-noshow-alerts': typeof ApiPublicHooksProcessNoshowAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/bi': typeof BiRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/equipe': typeof EquipeRoute
  '/fila': typeof FilaRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/metas': typeof MetasRoute
  '/performance': typeof PerformanceRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultados': typeof ResultadosRoute
  '/saas': typeof SaasRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/analytics/no-show': typeof AnalyticsNoShowRoute
  '/relatorios/agendamentos': typeof RelatoriosAgendamentosRoute
  '/relatorios/atendentes': typeof RelatoriosAtendentesRoute
  '/relatorios/comparecimento': typeof RelatoriosComparecimentoRoute
  '/relatorios/ltv': typeof RelatoriosLtvRoute
  '/relatorios/perdidos': typeof RelatoriosPerdidosRoute
  '/relatorios': typeof RelatoriosIndexRoute
  '/api/ai-training/simulate-chat': typeof ApiAiTrainingSimulateChatRoute
  '/api/public/hooks/build-reference-style': typeof ApiPublicHooksBuildReferenceStyleRoute
  '/api/public/hooks/enroll-silent-leads': typeof ApiPublicHooksEnrollSilentLeadsRoute
  '/api/public/hooks/process-appointment-reminders': typeof ApiPublicHooksProcessAppointmentRemindersRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-noshow-alerts': typeof ApiPublicHooksProcessNoshowAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/bi': typeof BiRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/equipe': typeof EquipeRoute
  '/fila': typeof FilaRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/metas': typeof MetasRoute
  '/performance': typeof PerformanceRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/resultados': typeof ResultadosRoute
  '/saas': typeof SaasRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/analytics/no-show': typeof AnalyticsNoShowRoute
  '/relatorios/agendamentos': typeof RelatoriosAgendamentosRoute
  '/relatorios/atendentes': typeof RelatoriosAtendentesRoute
  '/relatorios/comparecimento': typeof RelatoriosComparecimentoRoute
  '/relatorios/ltv': typeof RelatoriosLtvRoute
  '/relatorios/perdidos': typeof RelatoriosPerdidosRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/api/ai-training/simulate-chat': typeof ApiAiTrainingSimulateChatRoute
  '/api/public/hooks/build-reference-style': typeof ApiPublicHooksBuildReferenceStyleRoute
  '/api/public/hooks/enroll-silent-leads': typeof ApiPublicHooksEnrollSilentLeadsRoute
  '/api/public/hooks/process-appointment-reminders': typeof ApiPublicHooksProcessAppointmentRemindersRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-noshow-alerts': typeof ApiPublicHooksProcessNoshowAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/ai-insights'
    | '/ai-training'
    | '/bi'
    | '/chat'
    | '/clientes'
    | '/equipe'
    | '/fila'
    | '/kanban'
    | '/login'
    | '/marketing'
    | '/metas'
    | '/performance'
    | '/ranking'
    | '/relatorios'
    | '/reset-password'
    | '/resultados'
    | '/saas'
    | '/settings'
    | '/users'
    | '/whatsapp'
    | '/analytics/no-show'
    | '/relatorios/agendamentos'
    | '/relatorios/atendentes'
    | '/relatorios/comparecimento'
    | '/relatorios/ltv'
    | '/relatorios/perdidos'
    | '/relatorios/'
    | '/api/ai-training/simulate-chat'
    | '/api/public/hooks/build-reference-style'
    | '/api/public/hooks/enroll-silent-leads'
    | '/api/public/hooks/process-appointment-reminders'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-noshow-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/ai-insights'
    | '/ai-training'
    | '/bi'
    | '/chat'
    | '/clientes'
    | '/equipe'
    | '/fila'
    | '/kanban'
    | '/login'
    | '/marketing'
    | '/metas'
    | '/performance'
    | '/ranking'
    | '/reset-password'
    | '/resultados'
    | '/saas'
    | '/settings'
    | '/users'
    | '/whatsapp'
    | '/analytics/no-show'
    | '/relatorios/agendamentos'
    | '/relatorios/atendentes'
    | '/relatorios/comparecimento'
    | '/relatorios/ltv'
    | '/relatorios/perdidos'
    | '/relatorios'
    | '/api/ai-training/simulate-chat'
    | '/api/public/hooks/build-reference-style'
    | '/api/public/hooks/enroll-silent-leads'
    | '/api/public/hooks/process-appointment-reminders'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-noshow-alerts'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/ai-insights'
    | '/ai-training'
    | '/bi'
    | '/chat'
    | '/clientes'
    | '/equipe'
    | '/fila'
    | '/kanban'
    | '/login'
    | '/marketing'
    | '/metas'
    | '/performance'
    | '/ranking'
    | '/relatorios'
    | '/reset-password'
    | '/resultados'
    | '/saas'
    | '/settings'
    | '/users'
    | '/whatsapp'
    | '/analytics/no-show'
    | '/relatorios/agendamentos'
    | '/relatorios/atendentes'
    | '/relatorios/comparecimento'
    | '/relatorios/ltv'
    | '/relatorios/perdidos'
    | '/relatorios/'
    | '/api/ai-training/simulate-chat'
    | '/api/public/hooks/build-reference-style'
    | '/api/public/hooks/enroll-silent-leads'
    | '/api/public/hooks/process-appointment-reminders'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-noshow-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiTrainingRoute: typeof AiTrainingRoute
  BiRoute: typeof BiRoute
  ChatRoute: typeof ChatRoute
  ClientesRoute: typeof ClientesRoute
  EquipeRoute: typeof EquipeRoute
  FilaRoute: typeof FilaRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  MetasRoute: typeof MetasRoute
  PerformanceRoute: typeof PerformanceRoute
  RankingRoute: typeof RankingRoute
  RelatoriosRoute: typeof RelatoriosRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultadosRoute: typeof ResultadosRoute
  SaasRoute: typeof SaasRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WhatsappRoute: typeof WhatsappRoute
  AnalyticsNoShowRoute: typeof AnalyticsNoShowRoute
  ApiAiTrainingSimulateChatRoute: typeof ApiAiTrainingSimulateChatRoute
  ApiPublicHooksBuildReferenceStyleRoute: typeof ApiPublicHooksBuildReferenceStyleRoute
  ApiPublicHooksEnrollSilentLeadsRoute: typeof ApiPublicHooksEnrollSilentLeadsRoute
  ApiPublicHooksProcessAppointmentRemindersRoute: typeof ApiPublicHooksProcessAppointmentRemindersRoute
  ApiPublicHooksProcessFollowupsRoute: typeof ApiPublicHooksProcessFollowupsRoute
  ApiPublicHooksProcessNoshowAlertsRoute: typeof ApiPublicHooksProcessNoshowAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-training': {
      id: '/ai-training'
      path: '/ai-training'
      fullPath: '/ai-training'
      preLoaderRoute: typeof AiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/perdidos': {
      id: '/relatorios/perdidos'
      path: '/perdidos'
      fullPath: '/relatorios/perdidos'
      preLoaderRoute: typeof RelatoriosPerdidosRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/ltv': {
      id: '/relatorios/ltv'
      path: '/ltv'
      fullPath: '/relatorios/ltv'
      preLoaderRoute: typeof RelatoriosLtvRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/comparecimento': {
      id: '/relatorios/comparecimento'
      path: '/comparecimento'
      fullPath: '/relatorios/comparecimento'
      preLoaderRoute: typeof RelatoriosComparecimentoRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/atendentes': {
      id: '/relatorios/atendentes'
      path: '/atendentes'
      fullPath: '/relatorios/atendentes'
      preLoaderRoute: typeof RelatoriosAtendentesRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/agendamentos': {
      id: '/relatorios/agendamentos'
      path: '/agendamentos'
      fullPath: '/relatorios/agendamentos'
      preLoaderRoute: typeof RelatoriosAgendamentosRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/analytics/no-show': {
      id: '/analytics/no-show'
      path: '/analytics/no-show'
      fullPath: '/analytics/no-show'
      preLoaderRoute: typeof AnalyticsNoShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-training/simulate-chat': {
      id: '/api/ai-training/simulate-chat'
      path: '/api/ai-training/simulate-chat'
      fullPath: '/api/ai-training/simulate-chat'
      preLoaderRoute: typeof ApiAiTrainingSimulateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-noshow-alerts': {
      id: '/api/public/hooks/process-noshow-alerts'
      path: '/api/public/hooks/process-noshow-alerts'
      fullPath: '/api/public/hooks/process-noshow-alerts'
      preLoaderRoute: typeof ApiPublicHooksProcessNoshowAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-followups': {
      id: '/api/public/hooks/process-followups'
      path: '/api/public/hooks/process-followups'
      fullPath: '/api/public/hooks/process-followups'
      preLoaderRoute: typeof ApiPublicHooksProcessFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-appointment-reminders': {
      id: '/api/public/hooks/process-appointment-reminders'
      path: '/api/public/hooks/process-appointment-reminders'
      fullPath: '/api/public/hooks/process-appointment-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessAppointmentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enroll-silent-leads': {
      id: '/api/public/hooks/enroll-silent-leads'
      path: '/api/public/hooks/enroll-silent-leads'
      fullPath: '/api/public/hooks/enroll-silent-leads'
      preLoaderRoute: typeof ApiPublicHooksEnrollSilentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/build-reference-style': {
      id: '/api/public/hooks/build-reference-style'
      path: '/api/public/hooks/build-reference-style'
      fullPath: '/api/public/hooks/build-reference-style'
      preLoaderRoute: typeof ApiPublicHooksBuildReferenceStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RelatoriosRouteChildren {
  RelatoriosAgendamentosRoute: typeof RelatoriosAgendamentosRoute
  RelatoriosAtendentesRoute: typeof RelatoriosAtendentesRoute
  RelatoriosComparecimentoRoute: typeof RelatoriosComparecimentoRoute
  RelatoriosLtvRoute: typeof RelatoriosLtvRoute
  RelatoriosPerdidosRoute: typeof RelatoriosPerdidosRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
}

const RelatoriosRouteChildren: RelatoriosRouteChildren = {
  RelatoriosAgendamentosRoute: RelatoriosAgendamentosRoute,
  RelatoriosAtendentesRoute: RelatoriosAtendentesRoute,
  RelatoriosComparecimentoRoute: RelatoriosComparecimentoRoute,
  RelatoriosLtvRoute: RelatoriosLtvRoute,
  RelatoriosPerdidosRoute: RelatoriosPerdidosRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
}

const RelatoriosRouteWithChildren = RelatoriosRoute._addFileChildren(
  RelatoriosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiTrainingRoute: AiTrainingRoute,
  BiRoute: BiRoute,
  ChatRoute: ChatRoute,
  ClientesRoute: ClientesRoute,
  EquipeRoute: EquipeRoute,
  FilaRoute: FilaRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  MetasRoute: MetasRoute,
  PerformanceRoute: PerformanceRoute,
  RankingRoute: RankingRoute,
  RelatoriosRoute: RelatoriosRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultadosRoute: ResultadosRoute,
  SaasRoute: SaasRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WhatsappRoute: WhatsappRoute,
  AnalyticsNoShowRoute: AnalyticsNoShowRoute,
  ApiAiTrainingSimulateChatRoute: ApiAiTrainingSimulateChatRoute,
  ApiPublicHooksBuildReferenceStyleRoute:
    ApiPublicHooksBuildReferenceStyleRoute,
  ApiPublicHooksEnrollSilentLeadsRoute: ApiPublicHooksEnrollSilentLeadsRoute,
  ApiPublicHooksProcessAppointmentRemindersRoute:
    ApiPublicHooksProcessAppointmentRemindersRoute,
  ApiPublicHooksProcessFollowupsRoute: ApiPublicHooksProcessFollowupsRoute,
  ApiPublicHooksProcessNoshowAlertsRoute:
    ApiPublicHooksProcessNoshowAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
